name: CICD Pipeline - React.js Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm ci
      - run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      # Clean old files
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: 34.14.201.174
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/ReactjsCiCd/*
            sudo chown -R ubuntu:ubuntu /var/www/html/ReactjsCiCd

      # Upload new build
      - uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_USER: ubuntu
          REMOTE_HOST: 34.14.201.174
          SOURCE: dist/
          TARGET: /var/www/html/ReactjsCiCd
          ARGS: "--recursive"

      # Reset permissions
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: 34.14.201.174
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/html/ReactjsCiCd
            sudo chmod -R 755 /var/www/html/ReactjsCiCd
            sudo systemctl reload nginx
